export const TENANTS = {
  e2sports: {
    id: 'e2sports',
    name: 'E2 Sports',
    hashCode: null,
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    sports: {
      component: 'default',
      logo: 'E2 Sports',
      logoAccent: '#3b82f6',
      logoUnderline: 'bg-blue-600',
      headerBg: 'bg-gray-900',
      navItems: ['Bundesliga', 'Champions League', '2. Liga', 'DFB-Pokal'],
      heroGradient: 'from-blue-600 to-blue-400',
      tagBg: 'bg-white/90',
      tagText: 'text-blue-600',
      blockquoteBorder: 'border-blue-500',
      oddsHighlight: 'text-blue-600',
    },
    casino: { component: 'default' },
    intel: { urlPrefix: 'e2sports.com', siteName: 'E2 Sports' },
    pulse: { accentBg: 'bg-purple-600', accentShadow: 'shadow-purple-500/20', accentText: 'text-purple-400', accentColor: '#a855f7' },
    widget: { gradient: 'from-purple-600 to-blue-500', bubbleBg: 'from-purple-600 to-blue-500', pingColor: 'bg-purple-500', accentColor: '#a855f7', bgLight: 'bg-purple-50' },
    embed: { publisher: 'e2sports', geo: 'DE' },
  },
  kicker: {
    id: 'kicker',
    name: 'Kicker',
    hashCode: 'a1b2c3',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    sports: {
      component: 'default',
      logo: 'Kicker',
      logoAccent: '#dc2626',
      logoUnderline: 'bg-red-600',
      headerBg: 'bg-gray-900',
      navItems: ['Bundesliga', 'Champions League', '2. Liga', 'DFB-Pokal'],
      heroGradient: 'from-red-600 to-amber-500',
      tagBg: 'bg-white/90',
      tagText: 'text-red-600',
      blockquoteBorder: 'border-red-500',
      oddsHighlight: 'text-red-600',
    },
    casino: { component: 'default' },
    intel: { urlPrefix: 'kicker.de', siteName: 'Kicker' },
    pulse: { accentBg: 'bg-red-600', accentShadow: 'shadow-red-500/20', accentText: 'text-red-400', accentColor: '#dc2626' },
    widget: { gradient: 'from-red-600 to-red-500', bubbleBg: 'from-red-600 to-red-500', pingColor: 'bg-red-500', accentColor: '#dc2626', bgLight: 'bg-red-50' },
    embed: { publisher: 'kicker', geo: 'DE' },
  },
  livescore: {
    id: 'livescore',
    name: 'LiveScore',
    hashCode: 'x9y8z7',
    fontFamily: "'Sofia Sans', Arial, sans-serif",
    sports: {
      component: 'livescore',
      logo: 'LiveScore',
      logoUrl: 'https://www.livescore.com/ls-web-assets/images/live-score-outlined-74d06.webp',
      logoAccent: '#ff6b00',
      logoUnderline: 'bg-[#ff6b00]',
      headerBg: 'bg-[#1a1a2e]',
      navItems: ['Scores', 'News', 'Transfers', 'Betting'],
      heroGradient: 'from-[#ff6b00] to-[#cc5500]',
      tagBg: 'bg-[#ff6b00]',
      tagText: 'text-white',
      blockquoteBorder: 'border-[#ff6b00]',
      oddsHighlight: 'text-[#ff6b00]',
      accentColor: '#ff6b00',
      underlineColor: '#ff6b00',
    },
    casino: { component: 'default' },
    intel: { urlPrefix: 'livescore.com', siteName: 'LiveScore' },
    pulse: { accentBg: 'bg-[#ff6b00]', accentShadow: 'shadow-[#ff6b00]/20', accentText: 'text-[#ff6b00]', accentColor: '#ff6b00' },
    widget: { gradient: 'from-[#ff6b00] to-[#cc5500]', bubbleBg: 'from-[#ff6b00] to-[#cc5500]', pingColor: 'bg-[#ff6b00]', accentColor: '#ff6b00', bgLight: 'bg-orange-50' },
    embed: { publisher: 'livescore', geo: 'UK' },
  },
}

export function getTenantByHash(hash) {
  const code = (hash || '').replace(/^#\/?/, '').split('?')[0]
  if (!code) return TENANTS.e2sports
  const found = Object.values(TENANTS).find(t => t.hashCode === code)
  return found || TENANTS.e2sports
}
